import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { kurang, tambah } from '../components/index.slice'
import { useDispatch, useSelector } from 'react-redux'
import Link from 'next/link'

export default function Home() {

  const dispatch = useDispatch()
  const tambahKurangState = useSelector((state) => state.tambahKurang)

  const klikTambah = () => {
    dispatch(tambah())
  }

  const klikKurang = () => {
    dispatch(kurang())
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Tambah Kurang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <Link href={'/inquiry'}>
          <button>Inquiry Test</button>
        </Link>
        <br></br>
        <div className="my-5">
          <button className="" onClick={klikKurang}>Kurang</button>
          <b className="mx-3">{tambahKurangState.total}</b>
          <button className="" onClick={klikTambah}>Tambah</button>
        </div>
      </div>
    </div>
  )
}
